version: "3.4"

networks:
  backend:
    external: false
  frontend:

volumes:
  mongodb:
  storage:

services:
  mongodb-service:
    image: mongo:4.4
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: spyface
    networks:
      - backend

  api-service:
    image: api:0.1
    build:
      context: ./api
      target: dev
      args:
        REPOSITORY: fernandogbi
    command: uvicorn spyface.main:app --host 0.0.0.0 --port 8080 --reload
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 60s
      timeout: 15s
      retries: 2
      start_period: 30s
    volumes:
      - ./api/src/spyface:/spyface/
      - ./modelo:/opt/modelo
    networks:
      - backend

  api-gateway:
    image: devopsfaith/krakend
    ports:
      - 80:8080
    volumes:
      - ./krakend:/etc/krakend
    depends_on:
      - api-service
    networks:
      - backend
      - frontend
    environment:
      FC_ENABLE: 1
      SPYFACE_API_HOST: api-service
      SPYFACE_API_PORT: 8080

  treino:
    image: treino:0.1
    build:
      context: ./train
      target: dev
      args:
        REPOSITORY: fernandogbi
    networks:
      - backend
    depends_on:
      - mongodb-service
    volumes:
      - storage:/spyface/storage/imagens
      - ./modelo:/opt/modelo
      - ./train/src:/spyface
    environment:
      MONGO_HOST: mongodb-service