apiVersion: v1
kind: Service
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.krakend.service.type }}
  ports:
    - port: {{ .Values.krakend.service.port }}
      targetPort: {{ .Values.krakend.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "krakend.selectorLabels" . | nindent 4 }}
