version: '1.0'
stages:
  - clone
  - check
  - build
  - push
steps:
  clone_repository:
    stage: clone
    type: git-clone
    title: 'Cloning repository'
    description: 'Step to clone repository'
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: ${{CF_REVISION}}

  verify_builds:
    stage: check
    type: justforpersonalstudies/changes-verifier
    title: 'Getting changed files list'

  build_images:
    stage: build
    type: parallel
    steps:
      build_base_image:
        stage: build
        type: build
        title: 'building base image'
        working_directory: ${{CF_REPO_NAME}}/base-image
        image_name: fernandogbi/spyface-base
        disable_push: true
        when:
          condition:
            all:
              check_changes: 'includes("base-image/", "${{HAS_CHANGES}}") == true'

      build_api_image:
        stage: build
        type: build
        title: 'building api image'
        working_directory: ${{CF_REPO_NAME}}/api
        image_name: fernandogbi/spyface-api
        disable_push: true
        when:
          condition:
            all:
              check_changes: 'includes("api/", "${{HAS_CHANGES}}") == true'

      build_train_image:
        stage: build
        type: build
        title: 'building train image'
        working_directory: ${{CF_REPO_NAME}}/train
        image_name: fernandogbi/spyface-train
        disable_push: true
        when:
          condition:
            all:
              check_changes: 'includes("spyface-train/", "${{HAS_CHANGES}}") == true'

      build_krakend_image:
        stage: build
        type: build
        title: 'building krakend image'
        working_directory: ${{CF_REPO_NAME}}/krakend
        image_name: fernandogbi/krakend
        disable_push: true
        when:
          condition:
            all:
              check_changes: 'includes("krakend/", "${{HAS_CHANGES}}") == true'