apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-train-job
spec:
  template:
    spec:
      containers:
        - name: spyface-train
          image: fernandogbi/spyface-train:0.1
          volumeMounts:
            - mountPath: /opt/modelo
              name: {{ .Values.volumeName }}
      restartPolicy: OnFailure
      {{ if eq .Values.environment "dev" }}
      volumes:
        - name: {{ .Values.volumeName }}
          hostPath:
            path: {{ .Values.developmentVolumes.path }}
            type: {{ .Values.developmentVolumes.type }}
      {{ end }}