apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongochart.fullname" . }}
spec:
  type: {{ .Values.mongodb.service.type }}
  selector:
    {{- include "mongochart.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port }}